### ISSUE TITLE
Unable to deselect OS versions from filters

### ISSUE THREAD

**Issue by abhaysood** [measure-sh/measure#1282] opened 2024-09-24 06:10 UTC
# Description

Unable to deselect OS versions from filters, see video for details.

https://github.com/user-attachments/assets/0f1e1287-955c-4105-89fd-b01bf9b5e8d7

**Comment by anupcowkur** [comment] 2024-09-24 08:27
Unable to reproduce this. Closing.

**Closed by anupcowkur** 2024-09-24 08:27 UTC
Labels: bug, frontend
